<a href="https://colab.research.google.com/github/ayushmoti123/mini-project/blob/main/House_Prices_Predictor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

In [31]:
import numpy as np

In [20]:
#preprocessing
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

#splitting

from sklearn.model_selection import train_test_split

#Model
from sklearn.linear_model import LinearRegression

#Pipeline
from sklearn.pipeline import Pipeline

#Metrics

from sklearn.metrics import mean_squared_error,r2_score

In [19]:
#data=pd.read_csv("listings.csv")
data.head()
#data["neighbourhood_group"].isna().count()
#data["license"].isna().sum()
#(data["number_of_reviews_ltm"]==0).sum()
#data.isna().sum()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
0,27934,Nice room with superb city view,120437,Nuttee,NaN,Ratchathewi,13.75983,100.54134,Entire home/apt,1595.0,15,65,2024-09-17,0.40,1,362,0,NaN
1,27979,"Easy going landlord,easy place",120541,Emy,NaN,Bang Na,13.66818,100.61674,Private room,NaN,1,0,NaN,NaN,2,0,0,NaN
2,28745,modern-style apartment in Bangkok,123784,Familyroom,NaN,Bang Kapi,13.75232,100.62402,Private room,NaN,60,0,NaN,NaN,1,0,0,NaN
3,47516,Beautiful waterfront house,214456,Anuradha,NaN,Don Mueang,13.92726,100.58529,Entire home/apt,4188.0,3,0,NaN,NaN,1,365,0,NaN
4,48736,Condo with Chaopraya River View,222005,Athitaya,NaN,Rat Burana,13.68556,100.49535,Private room,1450.0,14,1,2014-02-03,0.01,1,365,0,NaN

In [17]:
#data_copy=data.copy()
#data_copy.drop("neighbourhood_group",axis=1,inplace=True)
#data_copy.drop("license",axis=1,inplace=True)
#data_copy.isna().sum()
data_copy["price","minimum_nights",""]

id                                    0
name                                  0
host_id                               0
host_name                             9
neighbourhood                         0
latitude                              0
longitude                             0
room_type                             0
price                              5533
minimum_nights                        0
number_of_reviews                     0
last_review                       10090
reviews_per_month                 10090
calculated_host_listings_count        0
availability_365                      0
number_of_reviews_ltm                 0
dtype: int64

In [22]:
features=['room_type','minimum_nights','calculated_host_listings_count','availability_365']
data_baseline=data_copy.dropna(subset=features+['price'])

In [25]:
from sklearn import preprocessing
X=data_baseline[features]
Y=data_baseline['price']
preprocesser=ColumnTransformer(
    [('cat',OneHotEncoder(handle_unknown='ignore'),['room_type']),
    ('num','passthrough',['minimum_nights','calculated_host_listings_count','availability_365'])
    ])

In [26]:
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.2,random_state=42)

In [30]:
model_lr=Pipeline([('preprocess',preprocesser),('model',LinearRegression())])
model_lr.fit(x_train,y_train)
pred_lr=model_lr.predict(x_test)

In [32]:
rmse_lr=np.sqrt(mean_squared_error(y_test,pred_lr))
print(rmse_lr)

19835.06128410933